---
- name: Install and run apache
  hosts: ansible1,ansible2
  tasks:
    - name: Install httpd (apache)
      yum:
        name: httpd
        state: latest
    - name: Run httpd
      service:
        name: httpd
        state: started
        enabled: true
    - name: Open http ports
      firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
    - name: Create index.html
      copy:
        src: files/index.html
        dest: /var/www/html 
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
