---
- name: Check httpd status
  hosts: db
  tasks:
    - name: Check if httpd package is present
      yum:
        name: httpd
        state: present
    - name: Check if httpd service is up and running
      service:
        name: httpd
        state: started
        enabled: true
- name: Check MariaDB status
  hosts: db
  tasks:
    - name: Check if mariadb package is present
      yum:
        name: mariadb
        state: present
