---
- name: Check if services are present
  hosts: 
#    - ansible1
    - ansible2
  tasks:
    - name: Check for httpd and firewalld installed
      yum:
        name:
          - httpd
          - firewalld
        state: present
    - name: Hack an index.html
      copy:
        content: "This page was hacked by Anonymous Group"
        dest: /var/www/html/index.html
