---
- name: Check if firewalld and chronyd are running
  hosts: 
    - ansible1
    - ansible2
  tasks:
    - name: Check if firewalld is running
      service:
        name: firewalld
        state: started
    - name: Check if chronyd is running
      service:
        name: chronyd
        state: started
    - name: Check if httpd is running
      service:
        name: httpd
        state: started
    - name: Check if atd is running
      service:
        name: atd
        state: started
