---
- name: Check if webservers return content
  hosts: localhost
  tasks:
    - name: Check if server responds on port 80 and return code is 200
      uri:
        url: http://ansible1.example.com
#          - http://ansible1.example.com
#          - http://ansible2
        return_content: yes 
        status_code: 200
