---
- name: Add a secret user to host ansible2
  hosts: ansible2
  vars_files: vars/vault/secrets.yaml
  tasks:
    - name: Print a username and password
      debug:
        msg: "Username: {{ secret_user }} Password: {{ secret_pass }}"
    - name: Add user from secret file
      user:
        name: "{{ secret_user }}"
#        password: password
        password: "{{ secret_pass }}"
