---
- name: Print results in loop
  hosts: localhost
  tasks:
    - name: Run a shell command
      shell:
        cmd: "echo Username is {{ item }}"
      loop:
        - natasha
        - harry
      register: shell_results
    - name: Print results
      debug:
        msg: "{{ item.stdout }}"
      loop: "{{ shell_results['results'] }}"
