---
- name: Test 'in' statement
  hosts: ansible1
  vars:
    supported_distros:
      - RedHat
      - Fedora
#      - Rocky
  tasks:
    - name: Install httpd if distributive is supported
      yum:
        name: httpd
        state: latest
      when: >
          ( ansible_distribution in supported_distros )
          or
          ( ansible_distribution_major_version == "8" )
    - name: Debug
      debug:
#        msg: "{{ ansible_distribution }}"
        msg: "{{ ansible_distribution_major_version }}"
