---
- name: Install mariadb if there is 300M free space
  hosts: ansible1
  tasks:
    - name: Debug
      debug:
        msg: [
             "{{ item['mount'] }}",
             "{{ item['size_available'] }}"
        ]
      loop: "{{ ansible_facts['mounts'] }}"
    - name: Check for free space and install
      yum:
        name: mariadb
        state: latest
      loop: "{{ ansible_facts['mounts'] }}"
      when: item['mount'] == "/" and item['size_available'] > 300000000
#      when: ansible_facts['mounts']['mount'] == "/" and ansible_facts['mounts']['size_availabel'] > 300000000
