---
- name: Test task failure and force handlers to run
  vars:
    package_name: httpd
  force_handlers: yes
  hosts: db
  tasks:
    - name: Install packages
      yum:
        name: "{{ package_name }}"
        state: latest
      notify: restart_httpd
    - name: Install bfgdhd
      yum:
        name: bfgdhd
        state: latest
  handlers:
    - name: restart_httpd
      service:
        name: httpd
        state: restarted
