---
- name: Task Failure Exercise
  hosts: db
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Install {{ web_package }}
      yum:
        name: "{{ web_package }}"
        state: present
      ignore_errors: yes
    - name: Install {{ db_package }}
      yum:
        name: "{{ db_package }}"
        state: present
