---
- name: Task Failure Exercise
  hosts: db
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Trying to install webserver
      block:
      - name: Install {{ web_package }}
        yum:
          name: "{{ web_package }}"
          state: present
        failed_when: web_package == "httpd"
      rescue:
        - name: Install {{ db_package }} package
          yum:
            name: "{{ db_package }}"
            state: present
      always:
        - name: Start {{ db_service }} service
          service:
            name: "{{ db_service }}"
            state: started
