---
- name: Update a file in devops homedir
  hosts: ansible1
  tasks:
    - name: Add line to the users.txt
      lineinfile:
        path: /home/devops/users.txt
        line: "This line was added by ansible script"
        state: present

    - name: Add users records to the users.txt
      lineinfile:
        path: /home/devops/users.txt
        line: "{{ item }}"
        state: present
      loop:
        - root
        - ansible
        - devops

    - name: Add block to the file
      blockinfile:
        path: /home/devops/users.txt
        block: |
          This is line 1
          This is line 2
          This is line 3
