---
- name: Configure SOE
  hosts: all
  remote_user: devops
  become: true
  vars:
    - system_owner: mikhail@example.com
  tasks:
    - name: Configure /etc/motd
      template:
        src: files/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644

