---
- name: Apply a system role timesync
  hosts: servers
#  vars:
#    timesync_ntp_servers:
#      - hostname: 0.rhel.pool.ntp.org
#        iburst: yes
#      - hostname: 1.rhel.pool.ntp.org
#        iburst: yes
#      - hostname: 2.rhel.pool.ntp.org
#        iburst: yes
  roles:
    - rhel-system-roles.timesync

  post_tasks:
    - name: Set timezone
      vars:
        host_timezone: Asia/Tbilisi
      timezone:
        name: "{{ host_timezone }}"
      notify: reboot host

  handlers:
    - name: reboot host
      reboot:
