---
- name: Test vars debug
  
  hosts: servers
  tasks:
    - debug:
        msg: "{{ host_timezone }}"
    - debug:
        msg: "{{ ansible_facts['fqdn'] }}"
    - debug:
        msg: "{{ ansible_facts['hostname'] }}"
