---
- name: Deploy an apache web server
  hosts: servers
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    python_package: python3-PyMySQL
  tasks:
    - name: Install web server
      yum:
        name: 
          - "{{ web_pkg}}"
          - "{{ firewall_pkg }}"
          - "{{ python_package }}"
        state: latest
