---
- name: Chapter 3 practical task
  hosts: ansible1
  vars:
    firewall_pkg: firewalld
    firewall_svc: firewalld
    web_pkg: httpd
    web_svc: httpd
    ssl_pkg: mod_ssl
    httpdconf_src: files/httpd.conf
    httpdconf_dest: /etc/httpd/conf/httpd.conf
    htaccess_src: files/.htaccess
    secrets_dir: /etc/httpd/secrets
    secrets_src: files/htpasswd
    secrets_dest: "{{ secrets_dir }}/htpasswd"
    web_root: /var/www/html
  tasks:
    - name: Install pakages
      yum:
        name:
          - "{{ firewall_pkg }}"
          - "{{ web_pkg }}"
          - "{{ ssl_pkg }}"
        state: latest

    - name: Copy httpd.conf to "{{ ansible_facts[' hostname '] }}" host
      copy:
        src: "{{ httpdconf_src }}"
        dest: "{{ httpdconf_dest }}"
        owner: root
        group: root
        mode: 0644

    - name: Create a folder for secrets
      file:
        state: directory
        path: "{{ secrets_dir }}"
        owner: apache
        group: apache
        recurse: yes
        mode: 0500

    - name: Copy a secrets file
      copy:
        src: "{{ secrets_src }}"
        dest: "{{ secrets_dest }}"
        owner: apache
        group: apache
        mode: 0400

#    - name: Debug
#      debug:
#        msg: "{{ web_root }}/.htaccess"
    - name: Copy a .htaccess file
      copy:
        src: "{{ htaccess_src }}"
        dest: "{{ web_root }}/.htaccess"
        owner: apache
        group: apache
        mode: 0400

#    - name: Show hostname
#      debug:
#        msg: [
#             "{{ ansible_facts['all_ipv4_addresses'] }}",
#             "{{ ansible_facts['hostname'] }}"
#        ]
    - name: Generate index.html file
      copy:
        #content: "{{ ansible_facts['hostname'] }}({{ ansible_facts['all_ipv4_addresses'] }}) has been customized by Ansible.\n"
        content: "{{ ansible_facts['hostname'] }}({{ ansible_facts['ens33']['ipv4']['address'] }}) has been customized by Ansible."
        dest: /var/www/html/index.html

    - name: Enable firewall service
      service:
        name: "{{ firewall_svc }}"
        state: started
        enabled: true

    - name: Allow https traffic in firewall
      firewalld:
        service: https
        permanent: true
        state: enabled
        immediate: true

    - name: Enable web service
      service:
        name: "{{ web_svc }}"
        state: started
        enabled: true
